#!/bin/busybox sh

/bin/busybox --install -s
ln -s /bin/busybox /sbin/init

/bin/mount -t devtmpfs devtmpfs /dev
/bin/mkdir /dev/pts

exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

exec /sbin/init $*
