#!/bin/sh

depmod

modprobe ps2fb mode_option=1920x1080p@60

modprobe sif
modprobe iop-memory
modprobe iop-module
modprobe iop-irq

modprobe sd_mod
modprobe ohci-ps2
modprobe ums-usbat
modprobe usbhid
modprobe hid-generic
